### ISSUE TITLE
经常服务端闪退并报错 java.lang.IllegalStateException: No transaction in context.

### ISSUE THREAD

**Issue by Hibari233** [way-zer/ScriptAgent4MindustryExt#12]
[02-01-2021 00:37:20] [E] java.lang.IllegalStateException: No transaction in context.
        at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.current(TransactionApi.kt:108)
        at org.jetbrains.exposed.sql.Query.getTransaction(Query.kt:16)
        at org.jetbrains.exposed.sql.Query.iterator(Query.kt:218)
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:237)
        at org.jetbrains.exposed.dao.Entity.getReadValues(Entity.kt:25)
        at org.jetbrains.exposed.dao.Entity.lookup(Entity.kt:106)
        at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:88)
        at wayzer.lib.dao.PlayerData.getProfileId(PlayerData.kt)
        at wayzer.lib.dao.PlayerData.secure(PlayerData.kt:55)
        at wayzer.lib.dao.PlayerData.secureProfile(PlayerData.kt:59)
        at wayzer.user.Level$3$1.run(level.kts:63)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:83)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)

**Comment by Hibari233** [comment]
一般来说服务端会先卡死 然后敲回车后报错

**Comment by Hibari233** [comment]
环境是Windows Server 2019 Datacenter

**Comment by way-zer** [comment]
### 临时解决方案
先关闭usid验证
```
sa config wayzer.checkUsid set false
```
应该可行
### More
我这边关闭了checkUsid，数据库用的外部postgre，使用是正常的
暂时不确定问题原因，我先调查下，等会再给你回复

**Comment by way-zer** [comment]
问题已经修复,将在下一个版本发布,
临时解决方案
```
sa config wayzer.checkUsid set false
```

**Comment by Hibari233** [comment]
感谢！
