### ISSUE TITLE
JDK16 无法加载

### ISSUE THREAD

**Issue by Canary233** [way-zer/ScriptAgent4MindustryExt#16]
[10-04-2021 14:50:43] [E] Failed to load mod file config/mods/ScriptAgent4Mindustry-2.9.jar. Skipping.
[10-04-2021 14:50:43] [E] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at mindustry.mod.Mods.loadMod(Mods.java:789)
        at mindustry.mod.Mods.loadMod(Mods.java:702)
        at mindustry.mod.Mods.load(Mods.java:356)
        at mindustry.Vars.init(Vars.java:305)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:47)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)
Caused by: cf.wayzer.libraryManager.LibraryLoadException: load to ClassLoader fail:
        at cf.wayzer.libraryManager.LibraryManager.loadToClassLoader(LibraryManager.java:116)
        at cf.wayzer.scriptAgent.ScriptAgent.load(ScriptAgent.kt:33)
        at cf.wayzer.scriptAgent.ScriptAgent.load$default(ScriptAgent.kt:26)
        at cf.wayzer.ScriptAgent4Mindustry.<init>(ScriptAgent4Mindustry.kt:26)
        ... 12 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @9303fa1
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at cf.wayzer.libraryManager.LibraryManager.loadToClassLoader(LibraryManager.java:111)
        ... 15 more

**Comment by Canary233** [comment]
用的是OpenJDK17

**Comment by way-zer** [comment]
这个是JAVA16新加的安全特性。解决方案
1. 使用java8或者java11。
2. 添加启动参数 --illegal-access=permit

**Comment by Canary233** [comment]
> 这个是JAVA16新加的安全特性。解决方案
> 
> 1. 使用java8或者java11。
> 2. 添加启动参数 --illegal-access=permit

好的，感谢

**Comment by way-zer** [comment]
v3.1.0 无需增加启动参数
