### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by 44wrw44** [way-zer/ScriptAgent4MindustryExt#32]
When creating save 105, the following appears:
```
[02-28-2024 17:48:32] [E] java.lang.NoSuchFieldError: Class mindustry.core.GameS
tate does not have member field 'boolean serverPaused'
        at cn.pisceskkk.ServerAutoSave.saveGame(ServerAutoSave.java:204)
        at cn.pisceskkk.ServerAutoSave.lambda$init$0(ServerAutoSave.java:41)
        at arc.Events.fire(Events.java:53)
        at arc.Events.fire(Events.java:43)
        at mindustry.core.Logic.runWave(Logic.java:268)
        at mindustry.core.Logic.update(Logic.java:475)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication
.java:87)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.ja
va:52)
```
Version 7.5

**Comment by way-zer** [comment]
That seems not this plugin. check `cn.pisceskkk.ServerAutoSave`

**Comment by 44wrw44** [comment]
Oh, sorry... Looks like the save files are conflicting
