### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Baldur404** [way-zer/ScriptAgent4MindustryExt#39]
log info:

Auto Host after 5 seconds
> Exception in thread "HeadlessApplication" java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:534)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:639)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at arc.util.Http$HttpRequest.block(Http.java:297)
        at wayzer.ext.ResourceHelper$httpGet$2$1.invoke(resourceHelper.kts:52)
        at wayzer.ext.ResourceHelper$httpGet$2$1.invoke(resourceHelper.kts:48)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:159)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
        at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:40)
        at wayzer.ext.ResourceHelper$httpGet$2.invokeSuspend(resourceHelper.kts:48)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(SAScript-wayzer/maps), StandaloneCoroutine{Cancelling}@555bb90e, MindustryDispatcher@5a31f9d1]

**Comment by way-zer** [comment]
Not a bug, you are using maps in resourceSite, and resourceSite is down.

**Comment by Baldur404** [comment]
ok, how to close it ,it make my server can't load success

**Comment by way-zer** [comment]
resourceSite is up.

**Comment by Baldur404** [comment]
At the code logic , it should not affect the entire server when the resource loading fails,maybe you should remove the exception catch when server load, change to output the exception on resource pull fail and return a fail infomation Instead of directly blocking program execution

**Comment by way-zer** [comment]
That is map loading, server must be block to load map. 

地图加载只能在主线程进行，而在加载前，无法确认能否完成加载。报错只是打印处理，实际上会尝试更换另一张地图。

网络换图是可选功能，而且需要手动开启的。使用该功能代表你应该了解该功能。
